name: edsr
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.0
  - numpy=1.19.2
  - pip:
    - opencv-python==4.1.2.30
    - tensorflow==2.9.0
    - Pillow==9.2.0
    - scikit-image==0.19.3
    # just for delegant
    - botocore
    - boto3
